.PHONY: all
all:
	+$(MAKE) -C ../ all

.PHONY: valgrind
valgrind:
	+$(MAKE) -C ../ valgrind

.PHONY: run
run:
	+$(MAKE) -C ../ run

.PHONY: debug
debug:
	+$(MAKE) -C ../ debug

.PHONY: clean
clean:
	+$(MAKE) -C ../ clean
